### ISSUE TITLE
In tag.py, NameError: name 'context' is not defined

### ISSUE THREAD

**Issue by tjbtjbtjb** [jbheard/markdown-docs#12]
I just trying to use you jbheard/markdown-docs@v1 system to produce automatic documentation within the github action framework.

I got the following error.

```Traceback (most recent call last):
  File "/generatedocs/src/main.py", line 29, in <module>
    data = get_data(classes, functions, output)
  File "/generatedocs/src/doc_loader.py", line 8, in get_data
    c_data = get_class_data(c)
  File "/generatedocs/src/doc_loader.py", line 23, in get_class_data
    f_data = get_function_data(func, _class.name)
  File "/generatedocs/src/doc_loader.py", line 29, in get_function_data
    doc = utils.parse_docstring(docstring, context + ' ' + func.name)
  File "/generatedocs/src/utils.py", line 93, in parse_docstring
    collection, result = Tag.parse(curr)
  File "/generatedocs/src/tag.py", line 41, in parse
    result = tag.parse_string(string)
  File "/generatedocs/src/tag.py", line 29, in parse_string
    .format(context, line))
NameError: name 'context' is not defined
```

It seems to me that in the code the `context` and `line` variable are not defined here. Or perhaps may have badly configured my github action yaml file or my python docstrings. But I cannot understand fully what's currently happens.

**Comment by jbheard** [comment]
The fact that your code hit this line means your code docs need to be revised. For example `@author jbheard` would be fine, but `@author` would throw this exception since it expects to have an author named on the same line. I should also make this a warning rather than an exception.. 

I've been busy so I haven't worked on this project in a bit, but I'll try to get around to some updates in the coming weeks. This issue specifically looks like I just need to pass line number and `context` from [here](https://github.com/jbheard/markdown-docs/blob/master/src/utils.py#L84) to [here](https://github.com/jbheard/markdown-docs/blob/master/src/tag.py#L39)

**Comment by tjbtjbtjb** [comment]
Thanks for reply.
I had a look to your code also and I've understood that my docstring may contain incorrect or badly interpreted lines. But without the exception output (or warning) about the line and type of error, it's pretty difficult to know where.
